### ISSUE TITLE
Permission values missing under Views: Share ACL

### ISSUE THREAD

**Issue by AgentTNT** [vast-data/terraform-provider-vastdata#2]
In resources/views.go, under permissions, only FULL is accepted. However there still needs to be support added for READ, and CHANGE, as per the API documents. When using this to add AD groups to our SMB shares via TF we are only able to do the groups that match the FULL permission set, thus incurring additional time to go back and manually apply permission sets for READ, and CHANGE. 

```
								"permissions": &schema.Schema{
									Type:      schema.TypeString,
									Computed:  true,
									Optional:  true,
									Sensitive: false,

									ValidateDiagFunc: utils.OneOf([]string{"FULL"}),
									Description:      ` Allowed Values are [FULL]`,
								},
```

**Comment by tengelpotlog** [comment]
An internal issue was opened at Vast Data bug tracking system ...... next time please open a bug directly to Vast Data via the support it will be faster

**Comment by AgentTNT** [comment]
Thank you @tengelpotlog for the update. Can you or someone please update the readme within the repo to reflect the desired support channels for submitting issues/bugs for this Terraform Provider if that is the case?
